services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - DB_NAME=shopper
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    depends_on:
      - mongo